import '../imports/api/collections/ContactsCollection';
import '../imports/api/collections/TransactionsCollection';
import '../imports/api/collections/WalletsCollection';
import '../imports/api/methods/ContactsMethods';
import '../imports/api/methods/TransactionsMethods';
import '../imports/api/publications/ContactsPublications';
import '../imports/api/publications/WalletsPublication';
import '../infra/CustomError';
import '../infra/accounts';
